'use strict';
const $=s=>document.querySelector(s),C=HealthLabCore,key='health-lab-v1';
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const blank=()=>({version:1,days:{},routine:[],experiments:[],timerSessions:[]});
function read(){try{return C.normalize(JSON.parse(localStorage.getItem(key)));}catch{return blank();}}
let data=read(),before=structuredClone(data),formDay=dayKey();
function day(date=dayKey()){return data.days[date]??={habits:[],minutes:0,measurements:{},routine:[]};}
function persist(status){try{const candidate=C.normalize(C.mergeDelta(read(),before,data));localStorage.setItem(key,JSON.stringify(candidate));data=candidate;before=structuredClone(data);if(status)$(status).textContent='この端末に保存しました。';return true;}catch{if(status)$(status).textContent='保存できませんでした。記録を書き出してからブラウザの保存設定を確認してください。';return false;}}
const habits=[['rest','休息の時間を確保する'],['move','無理のない散歩・体ほぐし'],['food','落ち着いて食事をとる'],['connect','誰かにひと言、気持ちを伝える'],['notice','1分、今の感覚に気づく']];
function node(tag,content,cls){const n=document.createElement(tag);if(content!=null)n.textContent=content;if(cls)n.className=cls;return n;}
function formatNum(v,digits=1){return v==null?'未測定':Number(v).toLocaleString('ja-JP',{maximumFractionDigits:digits});}
function renderToday(){const d=day(formDay);$('#date').textContent=new Date(formDay+'T12:00:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long'});$('#recommendation').textContent=d.mood==='hard'?'まずは安心できる場所へ。部屋を見渡し、足の感覚を確かめ、話せる相手を選びましょう。':d.energy==='low'?'今日は回復を優先。休む時間をひとつ確保し、動くなら体に心地よい範囲で。':'体調に合わせて、短い散歩か体ほぐしを。疲れたら休息へ。生活の土台を少しずつ整えましょう。';$('#habits').replaceChildren();for(const[id,title]of habits){const l=node('label',null,'habit'),c=document.createElement('input');c.type='checkbox';c.checked=d.habits.includes(id);c.addEventListener('change',()=>{const current=day(formDay);current.habits=c.checked?[...new Set([...current.habits,id])]:current.habits.filter(x=>x!==id);persist('#save-status');});l.append(c,document.createTextNode(title));$('#habits').append(l);}renderRoutine();overview();}
function overview(){const end=dayKey(),start=C.offsetDate(end,-6);$('#overview').replaceChildren();for(const k of ['sleep_hours','steps','exercise_min','resting_hr']){const m=C.metrics[k],a=C.values(data.days,k,start,end),v=k==='exercise_min'?a.reduce((s,v)=>s+v,0):C.average(a),d=node('div');d.append(node('span',k==='exercise_min'?'7日間の運動':`7日平均 ${m.label}`),node('strong',a.length?`${formatNum(v,k==='steps'?0:1)} ${m.unit}`:'未測定'),node('span',`${a.length}日の測定 / ${start}〜${end}`));$('#overview').append(d);}}
function restoreForms(){const d=day(formDay);$('#checkin').reset();for(const n of ['energy','mood','sleep'])if(d[n]!=null)$('#checkin').elements[n].value=d[n];for(const n of ['fact','feeling','step','thanks'])$('#journal-form').elements[n].value=d.journal?.[n]||'';}
function checkDate(){if(formDay===dayKey())return true;$('#save-status').textContent='日付が変わりました。画面を開き直して、今日の記録を入力してください。';$('#journal-status').textContent=$('#save-status').textContent;return false;}
$('#checkin').addEventListener('submit',e=>{e.preventDefault();if(!checkDate())return;const f=new FormData(e.target),d=day(formDay);d.energy=f.get('energy');d.mood=f.get('mood');d.sleep=f.get('sleep')===''?null:Number(f.get('sleep'));if(d.sleep!=null)d.measurements.sleep_hours=d.sleep;else delete d.measurements.sleep_hours;persist('#save-status');renderToday();});
$('#journal-form').addEventListener('submit',e=>{e.preventDefault();if(!checkDate())return;const values=Object.fromEntries(new FormData(e.target));if(!Object.values(values).some(x=>x.trim())){$('#journal-status').textContent='残したいことを一つ書いてください。';return;}day(formDay).journal=values;persist('#journal-status');});
function renderRoutine(){const list=$('#routine-list');list.replaceChildren();if(!data.routine.length){list.append(node('p','自分に合う習慣を登録して、今日の実践を記録できます。'));return;}for(const title of data.routine){const l=node('label',null,'routine-item'),c=document.createElement('input');c.type='checkbox';c.checked=day(formDay).routine.includes(title);c.addEventListener('change',()=>{const d=day(formDay);d.routine=c.checked?[...new Set([...d.routine,title])]:d.routine.filter(x=>x!==title);persist('#routine-status');});l.append(c,document.createTextNode(title));list.append(l);}}
$('#edit-routine').addEventListener('click',()=>{$('#routine-form').hidden=!$('#routine-form').hidden;$('#routine-input').value=data.routine.join('\n');});$('#routine-form').addEventListener('submit',e=>{e.preventDefault();data.routine=[...new Set($('#routine-input').value.split('\n').map(s=>s.trim().slice(0,100)).filter(Boolean))].slice(0,12);persist('#routine-status');$('#routine-form').hidden=true;renderRoutine();});
function review(){let count=0,minutes=0,rest=0;for(let i=0;i<7;i++){const d=data.days[C.offsetDate(dayKey(),-i)];if(!d)continue;if(d.energy||d.journal||d.habits?.length||d.minutes)count++;minutes+=d.minutes||0;if(d.habits?.includes('rest'))rest++;}$('#summary').replaceChildren();for(const[n,label]of [[count,'記録した日'],[Math.round(minutes),'静かな時間（分）'],[rest,'休息を選んだ日']]){const div=node('div');div.append(node('strong',n),document.createTextNode(label));$('#summary').append(div);}$('#history').replaceChildren();const entries=Object.entries(data.days).filter(([,d])=>d.energy||d.journal||d.habits.length||d.minutes).sort(([a],[b])=>b.localeCompare(a)).slice(0,30);if(!entries.length)$('#history').textContent='まだ日記や実践の記録はありません。';for(const[date,d]of entries){const div=node('div',null,'day');div.append(node('h3',date),node('p',`実践 ${d.habits.length}つ / 静かな時間 ${Math.round(d.minutes)}分${d.sleep!=null?' / 睡眠 '+d.sleep+'時間':''}`));for(const[k,l]of [['fact','事実'],['feeling','気持ち'],['step','一歩'],['thanks','ありがたかったこと']])if(d.journal?.[k])div.append(node('p',`${l}：${d.journal[k]}`));$('#history').append(div);}renderChart();}
function openPanel(id){for(const el of document.querySelectorAll('.panel'))el.hidden=el.id!==id;for(const el of document.querySelectorAll('[data-tab]'))el.setAttribute('aria-pressed',String(el.dataset.tab===id));if(id==='review')review();if(id==='experiments')renderExperiments();}
for(const b of document.querySelectorAll('[data-tab]')){b.removeAttribute('aria-selected');b.setAttribute('aria-pressed',String(b.dataset.tab==='today'));b.addEventListener('click',()=>openPanel(b.dataset.tab));}
let ticker=null,end=0,started=0,timerDay='',timerId='';const format=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
function finish(complete=false){if(!ticker)return;clearInterval(ticker);ticker=null;const elapsed=Math.min(Number($('#duration').value),Math.max(0,(Date.now()-started)/1000));const latest=read();if(!latest.timerSessions.includes(timerId)){const d=day(timerDay);d.minutes+=elapsed/60;data.timerSessions=[...new Set([...latest.timerSessions,...data.timerSessions,timerId])].slice(-1000);}const saved=persist('#timer-status');if(saved){$('#timer-status').textContent=complete?'おつかれさまでした。周囲を見渡し、ゆっくり日常へ。':'ここで終えて大丈夫です。実践した時間を記録しました。';try{localStorage.removeItem('health-lab-timer');}catch{}}$('#start').disabled=false;$('#duration').disabled=false;}
function tick(){const left=Math.max(0,Math.ceil((end-Date.now())/1000));$('#timer').textContent=format(left);if(!left)finish(true);}
function activateTimer(){ticker=setInterval(tick,250);$('#start').disabled=true;$('#duration').disabled=true;tick();}
$('#duration').addEventListener('change',()=>$('#timer').textContent=format(Number($('#duration').value)));
$('#start').addEventListener('click',()=>{if(ticker)return;started=Date.now();timerId=crypto.randomUUID();timerDay=dayKey();end=started+Number($('#duration').value)*1000;try{localStorage.setItem('health-lab-timer',JSON.stringify({id:timerId,started,end,timerDay,duration:Number($('#duration').value)}));}catch{}$('#timer-status').textContent='自然な呼吸を感じる。気づいたら、戻る。';activateTimer();});$('#stop').addEventListener('click',()=>finish());
try{const t=JSON.parse(localStorage.getItem('health-lab-timer'));if(t&&[60,180,300,600].includes(t.duration)&&C.dateValid(t.timerDay)&&Number.isFinite(t.started)&&t.end===t.started+t.duration*1000){started=t.started;end=t.end;timerDay=t.timerDay;timerId=t.id||String(t.started);$('#duration').value=t.duration;activateTimer();if(ticker)$('#timer-status').textContent='前回のタイマーを再開しました。';}}catch{}
function download(name,content,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').addEventListener('click',()=>{download(`health-lab-${dayKey()}.json`,JSON.stringify(data,null,2),'application/json');$('#data-status').textContent='日記と健康記録を含むバックアップです。保管場所を選んでください。';});
$('#import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error();const clean=C.normalize(JSON.parse(await file.text()));if(!confirm('同じ日付の記録・ルーティン・実験は読み込む内容で置き換えます。続けますか？'))return;finish();data.days={...data.days,...clean.days};data.routine=clean.routine;data.experiments=clean.experiments;persist('#data-status');restoreForms();renderToday();review();renderExperiments();loadMetrics();}catch{$('#data-status').textContent='ヘルスラボの有効な記録ファイルを選んでください（5MB以下）。';}e.target.value='';});
$('#delete').addEventListener('click',()=>{if(!confirm('この端末のヘルスラボの記録・ルーティン・実験をすべて削除しますか？'))return;finish();data=blank();try{localStorage.setItem(key,JSON.stringify(data));localStorage.removeItem('health-lab-timer');before=structuredClone(data);$('#data-status').textContent='この端末の記録を削除しました。';}catch{$('#data-status').textContent='削除を保存できませんでした。';}restoreForms();renderToday();review();loadMetrics();renderExperiments();});
function loadMetrics(){const f=$('#metrics-form'),d=data.days[f.elements.date.value];for(const k of [...Object.keys(C.metrics),'note'])f.elements[k].value=d?.measurements?.[k]??(k==='sleep_hours'?d?.sleep??'':'');}
$('#metrics-form').elements.date.value=dayKey();$('#metrics-form').elements.date.max=dayKey();$('#metrics-form').elements.date.addEventListener('change',loadMetrics);loadMetrics();
$('#metrics-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),date=f.get('date');if(!C.dateValid(date)||date>dayKey())return;const d=day(date);d.measurements=C.cleanMetrics(Object.fromEntries(f));if(d.measurements.sleep_hours!=null)d.sleep=d.measurements.sleep_hours;else delete d.sleep;persist('#metrics-status');renderChart();overview();if(date===formDay)restoreForms();});
function renderChart(){const k=$('#chart-metric').value,m=C.metrics[k],today=dayKey(),start=C.offsetDate(today,-29),a=C.values(data.days,k,start,today),last7=C.values(data.days,k,C.offsetDate(today,-6),today),prev7=C.values(data.days,k,C.offsetDate(today,-13),C.offsetDate(today,-7));$('#metric-summary').replaceChildren();for(const[v,l]of [[C.average(last7),'直近7日平均'],[C.average(prev7),'その前7日平均'],[a.length,'30日の測定日数']]){const d=node('div');d.append(node('strong',formatNum(v)),document.createTextNode(l));$('#metric-summary').append(d);}$('#chart').replaceChildren();$('#metric-table').replaceChildren();const entries=Object.entries(data.days).filter(([date,d])=>date>=start&&date<=today&&d.measurements?.[k]!=null).sort(([a],[b])=>a.localeCompare(b));if(!entries.length){$('#chart').append(node('p','まだこの指標の記録はありません。記録を保存すると、自分の推移が表示されます。'));return;}const table=node('table'),thead=node('thead'),tr=node('tr');for(const l of ['日付',`${m.label}（${m.unit}）`])tr.append(node('th',l));thead.append(tr);table.append(thead);const tbody=node('tbody');for(const[date,d]of entries){const r=node('tr');r.append(node('td',date),node('td',formatNum(d.measurements[k])));tbody.append(r);}table.append(tbody);$('#metric-table').append(table);const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 840 200');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${m.label}の30日間の推移。日付ごとの値は下の表で確認できます。`);let min=Math.min(...a),max=Math.max(...a);if(min===max){min-=1;max+=1;}const xy=(date,v)=>[50+(Date.parse(date)-Date.parse(start))/86400000/29*750,150-(v-min)/(max-min)*120];const t=(x,y,value)=>{const n=document.createElementNS(ns,'text');n.setAttribute('x',x);n.setAttribute('y',y);n.setAttribute('fill','#4d6470');n.setAttribute('font-size','14');n.textContent=value;svg.append(n);};t(0,24,formatNum(max));t(0,154,formatNum(min));t(50,185,start);t(710,185,today);let previous=null;for(const[date,d]of entries){const[x,y]=xy(date,d.measurements[k]);if(previous&&C.offsetDate(previous.date,1)===date){const line=document.createElementNS(ns,'line');for(const[n,v]of Object.entries({x1:previous.x,y1:previous.y,x2:x,y2:y,stroke:'#187b89','stroke-width':3}))line.setAttribute(n,v);svg.append(line);}const c=document.createElementNS(ns,'circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',5);c.setAttribute('fill','#187b89');const title=document.createElementNS(ns,'title');title.textContent=`${date} ${formatNum(d.measurements[k])} ${m.unit}`;c.append(title);svg.append(c);previous={date,x,y};}$('#chart').append(svg);}
$('#chart-metric').addEventListener('change',renderChart);
function csvText(){const keys=['date',...Object.keys(C.metrics),'note'];return '\uFEFF'+[keys.map(C.csvCell).join(','),...Object.entries(data.days).filter(([,d])=>Object.keys(d.measurements||{}).some(k=>C.metrics[k])).sort(([a],[b])=>a.localeCompare(b)).map(([date,d])=>keys.map(k=>C.csvCell(k==='date'?date:d.measurements[k])).join(','))].join('\r\n');}
$('#csv-export').addEventListener('click',()=>download(`health-lab-metrics-${dayKey()}.csv`,csvText(),'text/csv;charset=utf-8'));
let pendingCSV=null;$('#csv-import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const box=$('#csv-preview');box.hidden=false;box.replaceChildren();try{if(file.size>5000000)throw Error('5MB以下のCSVを選んでください');pendingCSV=C.importCSV(await file.text(),dayKey());const dates=Object.keys(pendingCSV).sort(),existing=dates.filter(d=>data.days[d]?.measurements&&Object.keys(data.days[d].measurements).length).length;box.append(node('p',`${dates.length}日分 / ${dates[0]}〜${dates.at(-1)}。既存記録と重なる日：${existing}日。同じ日・同じ指標は読み込む値に置き換えます。空欄は既存値を保持します。`));const b=node('button','この内容を読み込む','primary');b.addEventListener('click',()=>{for(const[date,v]of Object.entries(pendingCSV)){const d=day(date);d.measurements={...d.measurements,...v};if(v.sleep_hours!=null)d.sleep=v.sleep_hours;}persist('#metrics-status');box.hidden=true;pendingCSV=null;renderChart();overview();loadMetrics();restoreForms();});box.append(b);}catch(err){pendingCSV=null;box.append(node('p',err.message));}e.target.value='';});
$('#experiment-form').elements.start.value=dayKey();$('#experiment-form').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(!C.dateValid(f.start))return;data.experiments.push({...f,length:Number(f.length),id:crypto.randomUUID(),status:'active',conclusion:''});persist('#experiment-status');e.target.reset();e.target.elements.start.value=dayKey();renderExperiments();});
function renderExperiments(){const list=$('#experiment-list');list.replaceChildren();if(!data.experiments.length){list.append(node('p','最初の実験を登録しましょう。まず測定を7日ほど続けると、開始前の比較ができます。'));return;}for(const e of [...data.experiments].reverse()){const div=node('div',null,'experiment'),m=C.metrics[e.metric],end=C.offsetDate(e.start,e.length-1),r=C.compare(data.days,e,dayKey());div.append(node('h3',e.title),node('p',`${e.start}〜${e.ended&&e.ended<end?e.ended:end} / ${m.label} / ${e.status==='stopped'?'中止':e.status==='done'?'完了':dayKey()>end?'観察期間終了':dayKey()<e.start?'開始前':'観察中'}`,'status'));const compare=node('div',null,'comparison');for(const[v,n,l]of [[r.baseline,r.baselineN,'開始前7日'],[r.during,r.duringN,'実験期間']]){const d=node('div');d.append(node('strong',v==null?'未測定':`${formatNum(v)} ${m.unit}`),node('span',`${l} / ${n}日の記録`));compare.append(d);}div.append(compare,node('p',r.difference==null?'前後両方の記録が必要です。':`平均値の差：${r.difference>0?'+':''}${formatNum(r.difference)} ${m.unit}。原因や健康効果はこの比較だけでは分かりません。`),node('p',`中止条件：${e.stop}`));const label=node('label','気づいたこと・次に変えたいこと'),input=document.createElement('textarea');input.value=e.conclusion;input.maxLength=2000;label.append(input);div.append(label);const buttons=node('div',null,'buttons');for(const[status,text]of [['active','観察中にする'],['done','完了として保存'],['stopped','中止として保存']]){const b=node('button',text);b.addEventListener('click',()=>{e.status=status;e.ended=status==='active'?null:dayKey();e.conclusion=input.value;const index=data.experiments.findIndex(x=>x.id===e.id);data.experiments[index]=e;persist('#experiment-status');renderExperiments();});buttons.append(b);}div.append(buttons);list.append(div);}}
let breakTimer=null,breakEnd=0;function breakTick(){const left=Math.max(0,Math.ceil((breakEnd-Date.now())/1000));$('#break-clock').textContent=format(left);if(!left){clearInterval(breakTimer);breakTimer=null;$('#break-start').disabled=false;$('#break-duration').disabled=false;$('#break-status').textContent='作業の区切りです。姿勢を変え、可能なら少し歩きましょう。';if('Notification'in window&&Notification.permission==='granted')new Notification('ヘルスラボ：休憩の時間',{body:'姿勢を変え、可能なら少し歩きましょう。',icon:'/health-lab/icon-192.png'});}}
$('#break-duration').addEventListener('change',()=>$('#break-clock').textContent=format(Number($('#break-duration').value)*60));$('#break-start').addEventListener('click',()=>{if(breakTimer)return;breakEnd=Date.now()+Number($('#break-duration').value)*60000;breakTimer=setInterval(breakTick,1000);$('#break-start').disabled=true;$('#break-duration').disabled=true;$('#break-status').textContent='作業中。画面を閉じるとタイマーは終了します。';breakTick();});$('#break-stop').addEventListener('click',()=>{clearInterval(breakTimer);breakTimer=null;$('#break-start').disabled=false;$('#break-duration').disabled=false;$('#break-clock').textContent=format(Number($('#break-duration').value)*60);$('#break-status').textContent='タイマーを止めました。';});$('#notify').addEventListener('click',async()=>{if(!('Notification'in window)){$('#break-status').textContent='このブラウザでは通知を使えません。';return;}try{const p=await Notification.requestPermission();$('#break-status').textContent=p==='granted'?'休憩終了をブラウザ通知で知らせます。':'通知は許可されていません。画面内でお知らせします。';}catch{$('#break-status').textContent='通知を有効にできませんでした。';}});
$('#doctor-report').addEventListener('click',()=>{const today=dayKey(),start=C.offsetDate(today,-29),lines=[`ヘルスラボ：相談用の記録 ${start}〜${today}`,'本人が入力・読み込んだ値です。診断・健康効果・生物学的年齢の判定は含みません。',''];for(const[date,d]of Object.entries(data.days).sort(([a],[b])=>a.localeCompare(b))){if(date<start||date>today)continue;if(!Object.keys(d.measurements||{}).length)continue;lines.push(date);for(const[k,m]of Object.entries(C.metrics))if(d.measurements[k]!=null)lines.push(`  ${m.label}: ${d.measurements[k]} ${m.unit}`);if(d.measurements.note)lines.push(`  測定メモ: ${d.measurements.note}`);}lines.push('','生活習慣の実験');for(const e of data.experiments)lines.push(`${e.title} / ${e.start} / ${e.length}日 / ${e.status}`,`中止条件: ${e.stop}`,`気づき: ${e.conclusion}`);download(`health-lab-consultation-${today}.txt`,lines.join('\n'));$('#report-status').textContent='健康記録を含むテキストを保存しました。共有する前に内容を確認してください。';});

$('#calendar-form').elements.date.value=dayKey();
$('#calendar-form').addEventListener('submit',e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));if(!C.dateValid(f.date))throw Error();const stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//HEALTH LAB//Health Rhythm//JA','CALSCALE:GREGORIAN'];for(let i=0;i<7;i++){const date=C.offsetDate(f.date,i);for(const [key,label,length]of [['wake','ヘルスラボ：起床時刻を確認',10],['move','ヘルスラボ：体調に合わせた活動',20],['winddown','ヘルスラボ：仕事を切り上げる',20]]){const time=f[key];const start=f.timezone==='tokyo'?new Date(date+'T'+time+':00+09:00'):new Date(date+'T'+time+':00');if(Number.isNaN(start.getTime()))throw Error();if(f.timezone==='local'&&(dayKey(start)!==date||String(start.getHours()).padStart(2,'0')+':'+String(start.getMinutes()).padStart(2,'0')!==time))throw Error();rows.push('BEGIN:VEVENT','UID:health-lab-'+key+'-'+date+'-'+time.replace(':','')+'-'+f.timezone+'@toriumis.com','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(start),'DTEND:'+stamp(new Date(start.getTime()+length*60000)),'SUMMARY:'+label,'DESCRIPTION:体調と予定に合わせて変更してください。','END:VEVENT');}}rows.push('END:VCALENDAR');download('health-lab-rhythm-'+f.date+'.ics',rows.join('\r\n')+'\r\n','text/calendar;charset=utf-8');$('#calendar-status').textContent='7日分・21件の予定を保存しました。Macのカレンダーで「ファイル → 読み込む」を選べます。';}catch{$('#calendar-status').textContent='日付と時刻を確認してください。夏時間の切替で存在しない時刻は選べません。';}});
window.addEventListener('storage',e=>{if(e.key!==key)return;$('#save-status').textContent='別の画面で記録が更新されました。次の保存時に変更を統合します。';});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/health-lab/sw.js').catch(()=>{$('#save-status').textContent='オフライン機能を準備できませんでした。オンラインで利用できます。';});
restoreForms();renderToday();
