'use strict';
const $=s=>document.querySelector(s), key='health-lab-v1';
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
let data={version:1,days:{}};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved?.version===1&&saved.days&&typeof saved.days==='object'&&!Array.isArray(saved.days))data=saved;}catch{}
function day(){return data.days[dayKey()]??={habits:[],minutes:0};}
function persist(status){try{localStorage.setItem(key,JSON.stringify(data));if(status)$(status).textContent='この端末に保存しました。';return true;}catch{if(status)$(status).textContent='保存できませんでした。ブラウザの保存設定を確認し、記録を書き出してください。';return false;}}
$('#date').textContent=new Date().toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long'});
const habits=[['rest','休息の時間を確保する'],['move','無理のない散歩・体ほぐし'],['food','落ち着いて食事をとる'],['connect','誰かにひと言、気持ちを伝える'],['notice','1分、今の感覚に気づく']];
function renderToday(){const d=day(),low=d.energy==='low',hard=d.mood==='hard';$('#recommendation').textContent=hard?'まずは安心できる場所へ。部屋を見渡し、足の感覚を確かめ、話せる相手を選びましょう。':low?'今日は回復を優先。休む時間をひとつ確保し、動くなら体に心地よい範囲で。':'気分と体調に合わせて、短い散歩か体ほぐしを。終わったら、今の感覚に1分気づいてみましょう。';$('#habits').replaceChildren();for(const [id,title]of habits){const l=document.createElement('label');l.className='habit';const c=document.createElement('input');c.type='checkbox';c.checked=d.habits?.includes(id)||false;c.addEventListener('change',()=>{const current=day();current.habits=c.checked?[...new Set([...(current.habits||[]),id])]:(current.habits||[]).filter(x=>x!==id);persist('#save-status');});l.append(c,document.createTextNode(title));$('#habits').append(l);}}
$('#checkin').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),d=day();d.energy=f.get('energy');d.mood=f.get('mood');d.sleep=f.get('sleep')===''?null:Number(f.get('sleep'));persist('#save-status');renderToday();});
function restoreForms(){const d=day();for(const n of ['energy','mood','sleep'])if(d[n]!=null)$('#checkin').elements[n].value=d[n];for(const n of ['fact','feeling','step','thanks'])$('#journal-form').elements[n].value=d.journal?.[n]||'';}
$('#journal-form').addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));if(!Object.values(values).some(x=>x.trim())){$('#journal-status').textContent='残したいことを一つ書いてください。';return;}day().journal=values;persist('#journal-status');});
function review(){let count=0,minutes=0,rest=0;for(let i=0;i<7;i++){const date=new Date();date.setDate(date.getDate()-i);const d=data.days[dayKey(date)];if(!d)continue;if(d.energy||d.journal||d.habits?.length||d.minutes)count++;minutes+=Number(d.minutes)||0;if(d.habits?.includes('rest'))rest++;}$('#summary').replaceChildren();for(const [n,label]of [[count,'記録した日'],[Math.round(minutes),'静かな時間（分）'],[rest,'休息を選んだ日']]){const div=document.createElement('div'),b=document.createElement('strong');b.textContent=n;div.append(b,document.createTextNode(label));$('#summary').append(div);}$('#history').replaceChildren();const entries=Object.entries(data.days).filter(([,d])=>d.energy||d.journal||d.habits?.length||d.minutes).sort(([a],[b])=>b.localeCompare(a)).slice(0,30);if(!entries.length)$('#history').textContent='まだ記録はありません。今日の小さな一歩から。';for(const [date,d]of entries){const div=document.createElement('div');div.className='day';const h=document.createElement('h3');h.textContent=date;div.append(h);const p=document.createElement('p');p.textContent=`実践 ${d.habits?.length||0}つ / 静かな時間 ${Math.round(d.minutes||0)}分${d.sleep!=null?' / 睡眠 '+d.sleep+'時間':''}`;div.append(p);for(const [k,l]of [['fact','事実'],['feeling','気持ち'],['step','一歩'],['thanks','ありがたかったこと']])if(d.journal?.[k]){const j=document.createElement('p');j.textContent=`${l}：${d.journal[k]}`;div.append(j);}$('#history').append(div);}}
for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',()=>{for(const el of document.querySelectorAll('.panel'))el.hidden=el.id!==b.dataset.tab;for(const el of document.querySelectorAll('[data-tab]'))el.setAttribute('aria-selected',String(el===b));if(b.dataset.tab==='review')review();});
let ticker=null,end=0,started=0,timerDay='';const format=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
function finish(complete=false){if(!ticker)return;clearInterval(ticker);ticker=null;const elapsed=Math.min(Number($('#duration').value),Math.max(0,(Date.now()-started)/1000));const d=data.days[timerDay]??={habits:[],minutes:0};d.minutes=(Number(d.minutes)||0)+elapsed/60;persist('#timer-status');$('#timer-status').textContent=complete?'おつかれさまでした。周囲を見渡し、ゆっくり日常へ。':'ここで終えて大丈夫です。実践した時間を記録しました。';$('#start').disabled=false;$('#duration').disabled=false;}
$('#duration').addEventListener('change',()=>$('#timer').textContent=format(Number($('#duration').value)));
$('#start').addEventListener('click',()=>{if(ticker)return;started=Date.now();timerDay=dayKey();end=started+Number($('#duration').value)*1000;$('#start').disabled=true;$('#duration').disabled=true;$('#timer-status').textContent='自然な呼吸を感じる。気づいたら、戻る。';ticker=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));$('#timer').textContent=format(left);if(!left)finish(true);},250);});$('#stop').addEventListener('click',()=>finish());
$('#export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`health-lab-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#data-status').textContent='書き出した記録には日記が含まれます。保管場所を選んでください。';});
$('#import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error();const x=JSON.parse(await file.text());if(x.version!==1||!x.days||typeof x.days!=='object'||Array.isArray(x.days))throw Error();const clean={};for(const [date,d]of Object.entries(x.days)){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!d||typeof d!=='object')throw Error();const entry={habits:Array.isArray(d.habits)?d.habits.filter(h=>habits.some(([id])=>id===h)):[],minutes:Math.min(1440,Math.max(0,Number(d.minutes)||0))};if(['low','mid','high'].includes(d.energy))entry.energy=d.energy;if(['calm','busy','hard'].includes(d.mood))entry.mood=d.mood;if(d.sleep!=null&&Number.isFinite(Number(d.sleep))&&d.sleep>=0&&d.sleep<=24)entry.sleep=Number(d.sleep);if(d.journal){entry.journal={};for(const n of ['fact','feeling','step','thanks'])entry.journal[n]=typeof d.journal[n]==='string'?d.journal[n].slice(0,4000):'';}clean[date]=entry;}if(!confirm('同じ日付の記録は読み込む内容で置き換えます。続けますか？'))return;finish();data.days={...data.days,...clean};persist('#data-status');restoreForms();renderToday();review();}catch{$('#data-status').textContent='ヘルスラボの有効な記録ファイルを選んでください（2MB以下）。';}e.target.value='';});
$('#delete').addEventListener('click',()=>{if(!confirm('この端末のヘルスラボの記録をすべて削除しますか？'))return;finish();data={version:1,days:{}};persist('#data-status');restoreForms();$('#checkin').reset();renderToday();review();});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/health-lab/sw.js').catch(()=>{});
restoreForms();renderToday();
