(function(root){
'use strict';
const metrics={sleep_hours:{label:'睡眠',unit:'時間',min:0,max:24},steps:{label:'歩数',unit:'歩',min:0,max:200000},exercise_min:{label:'運動',unit:'分',min:0,max:1440},resting_hr:{label:'安静時心拍',unit:'bpm',min:20,max:250},weight_kg:{label:'体重',unit:'kg',min:10,max:500},hrv_ms:{label:'HRV（SDNN）',unit:'ms',min:0,max:1000}};
const habitIds=['rest','move','food','connect','notice'];
const dateValid=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
const offsetDate=(s,n)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const finite=(v,min,max)=>v!==null&&v!==''&&v!==undefined&&typeof v!=='boolean'&&Number.isFinite(Number(v))&&Number(v)>=min&&Number(v)<=max?Number(v):null;
const text=(v,max=4000)=>typeof v==='string'?v.slice(0,max):'';
function cleanMetrics(x){const out={};if(!x||typeof x!=='object')return out;for(const [k,m]of Object.entries(metrics)){const v=finite(x[k],m.min,m.max);if(v!==null){if(k==='steps'&&v%1)throw Error('歩数は整数で入力してください');out[k]=v;}}if(typeof x.note==='string')out.note=text(x.note,1000);return out;}
function normalize(x){if(!x||x.version!==1||!x.days||typeof x.days!=='object'||Array.isArray(x.days))throw Error('形式が異なります');const out={version:1,days:{},routine:[],experiments:[],timerSessions:[]};for(const [date,d]of Object.entries(x.days)){if(!dateValid(date)||!d||typeof d!=='object')continue;const e={habits:Array.isArray(d.habits)?d.habits.filter(h=>habitIds.includes(h)):[],minutes:finite(d.minutes,0,1440)||0};if(['low','mid','high'].includes(d.energy))e.energy=d.energy;if(['calm','busy','hard'].includes(d.mood))e.mood=d.mood;const sleep=finite(d.sleep,0,24);if(sleep!==null)e.sleep=sleep;e.measurements=cleanMetrics(d.measurements);if(sleep!==null&&e.measurements.sleep_hours==null)e.measurements.sleep_hours=sleep;if(d.journal&&typeof d.journal==='object'){e.journal={};for(const k of ['fact','feeling','step','thanks'])e.journal[k]=text(d.journal[k]);}e.routine=Array.isArray(d.routine)?d.routine.filter(v=>typeof v==='string').slice(0,12):[];out.days[date]=e;}if(Array.isArray(x.routine))out.routine=x.routine.filter(v=>typeof v==='string'&&v.trim()).map(v=>v.slice(0,100)).slice(0,12);if(Array.isArray(x.experiments))for(const e of x.experiments.slice(0,100)){if(!e||!dateValid(e.start)||!metrics[e.metric]||![7,14,28].includes(Number(e.length)))continue;out.experiments.push({id:text(e.id,100)||e.start,title:text(e.title,120),metric:e.metric,start:e.start,length:Number(e.length),stop:text(e.stop,400),status:['active','done','stopped'].includes(e.status)?e.status:'active',conclusion:text(e.conclusion,2000),ended:dateValid(e.ended)?e.ended:null});}out.timerSessions=Array.isArray(x.timerSessions)?x.timerSessions.filter(v=>typeof v==='string').slice(-1000):[];return out;}
function mergeDelta(latest,before,after,path=''){if(path.endsWith('.minutes')&&typeof after==='number')return Math.max(0,(typeof latest==='number'?latest:(before||0))+(after-(before||0)));if((path.endsWith('.habits')||path.endsWith('.routine')||path==='timerSessions')&&Array.isArray(after)){const old=Array.isArray(before)?before:[];return [...new Set([...(Array.isArray(latest)?latest:[]).filter(v=>!old.includes(v)||after.includes(v)),...after.filter(v=>!old.includes(v))])];}if(path==='experiments'&&Array.isArray(before)&&Array.isArray(after)){const map=new Map((latest||[]).map(e=>[e.id,e]));for(const e of after)if(JSON.stringify(before.find(b=>b.id===e.id))!==JSON.stringify(e))map.set(e.id,e);for(const e of before)if(!after.some(a=>a.id===e.id))map.delete(e.id);return [...map.values()];}if(JSON.stringify(before)===JSON.stringify(after))return latest;if(!after||typeof after!=='object'||Array.isArray(after))return after;const result={...(latest&&typeof latest==='object'&&!Array.isArray(latest)?latest:{})};for(const k of new Set([...Object.keys(before||{}),...Object.keys(after)])){if(!Object.prototype.hasOwnProperty.call(after,k)){if(Object.prototype.hasOwnProperty.call(before||{},k))delete result[k];}else result[k]=mergeDelta(result[k],before?.[k],after[k],path?path+'.'+k:k);}return result;}
function values(days,k,start,end){return Object.entries(days).filter(([d])=>d>=start&&d<=end).map(([,d])=>d.measurements?.[k]??(k==='sleep_hours'?d.sleep:null)).filter(v=>v!==null&&v!==undefined&&Number.isFinite(v));}
const average=a=>a.length?a.reduce((s,n)=>s+n,0)/a.length:null;
function compare(days,e,today){const baseline=values(days,e.metric,offsetDate(e.start,-7),offsetDate(e.start,-1)),during=values(days,e.metric,e.start,[offsetDate(e.start,e.length-1),today,...(dateValid(e.ended)?[e.ended]:[])].sort()[0]);const a=average(baseline),b=average(during);return {baseline:a,during:b,baselineN:baseline.length,duringN:during.length,difference:a!==null&&b!==null?b-a:null};}
function parseCSV(s){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quote&&s[i+1]==='"'){cell+='"';i++;}else if(!quote&&cell!=='')throw Error('CSVの引用符が不正です');else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(quote)throw Error('CSVの引用符が閉じていません');row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows;}
function importCSV(s,today){const rows=parseCSV(s.replace(/^\uFEFF/,''));if(rows.length<2)throw Error('データ行がありません');const heads=rows.shift().map(h=>h.trim());if(heads[0]!=='date'||!heads.some(h=>metrics[h]))throw Error('dateと指標の列が必要です');if(new Set(heads).size!==heads.length)throw Error('列名が重複しています');const out={};for(const [index,row]of rows.entries()){if(row.length!==heads.length)throw Error(`${index+2}行目：列数が合いません`);const date=row[0].trim();if(!dateValid(date)||date>today)throw Error(`${index+2}行目：日付が不正または未来です`);const d={};heads.forEach((k,i)=>{if(metrics[k]&&row[i].trim()!==''){const v=finite(row[i].trim(),metrics[k].min,metrics[k].max);if(v===null||(k==='steps'&&v%1))throw Error(`${index+2}行目：${k}の値が不正です`);d[k]=v;}if(k==='note')d.note=row[i].slice(0,1000);});if(Object.keys(d).length)out[date]={...(out[date]||{}),...d};}if(!Object.keys(out).length)throw Error('測定値がありません');return out;}
function csvCell(v){let s=v==null?'':String(v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
const api={metrics,dateValid,offsetDate,finite,normalize,cleanMetrics,mergeDelta,values,average,compare,parseCSV,importCSV,csvCell};root.HealthLabCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
